1.8.3 - fix unbound variables and refactor tempfile creation/cleanup
See release-notes-1.8.3.md

diff --git a/src/main/bash/bin/make-cpan-dist.in b/src/main/bash/bin/make-cpan-dist.in
--- a/src/main/bash/bin/make-cpan-dist.in
+++ b/src/main/bash/bin/make-cpan-dist.in
@@ -143,8 +143,8 @@ filter_file_list() {
     return 1
   fi
 
-  file_list_sorted=$(mktemp)
-  exclude_list_sorted=$(mktemp)
+  file_list_sorted=$(make_temp)
+  exclude_list_sorted=$(make_temp)
 
   export LC_ALL=C
 
@@ -152,8 +152,6 @@ filter_file_list() {
   sort -u $exclude_list > $exclude_list_sorted
 
   comm -23 $file_list_sorted $exclude_list_sorted > "$file_list";
-
-  rm $file_list_sorted $exclude_list_sorted
 }
 
 ########################################################################
@@ -245,29 +243,33 @@ function find_git_home {
     done
 }
 
-# cleanup on exit
+########################################################################
+function make_temp {
+########################################################################
+    local tmp
+    tmp="$(mktemp "$@")"
+    CLEANFILES+=("$tmp")
+    echo "$tmp"
+}
+
 ########################################################################
 function cleanup {
 ########################################################################
-    scripts="${scripts:-}"
-    resources="${resources:-}"
-    tmp_gitdir="${tmp_gitdir:-}"
-    package_files="${package_files:-}"
-    exe_files="${exe_files:-}"
-    depfile="${depfile:-}"
-    workdir="${workdir:-}"
+    # Safely check NOCLEANUP in case it's unbound when exiting early
+    [[ -n "${NOCLEANUP:-}" ]] && return
 
-    [[ -n "$NOCLEANUP" ]] && return;
+    for item in "${CLEANFILES[@]:-}"; do
+        if [[ -d "$item" ]]; then
+            rm -rf "$item"
+        elif [[ -f "$item" ]]; then
+            rm -f "$item"
+        fi
+    done
 
-    [[ -n "$testsfile"     ]] && rm -f "$testsfile"
-    [[ -n "$package_files" ]] && rm -f "$package_files"
-    [[ -n "$exe_files"     ]] && rm -f "$exe_files"
-    [[ -n "$scripts"       ]] && rm -f "$scripts"
-    [[ -n "$depfile"       ]] && rm -f "$depfile"
-    [[ -n "$resources"     ]] && rm -f "$resources"
-    [[ -n "$builddir"      ]] && rm -rf "$builddir"
-    [[ -n "$tmp_gitdir"    ]] && rm -rf "$tmp_gitdir"
-    [[ -n "$workdir"       ]] && find "$workdir" -maxdepth 1 -name '*.tmp' -exec rm -f {} \;
+    # Retain your dynamic sweep for the temporary workdir files
+    if [[ -n "${workdir:-}" ]] && [[ -d "$workdir" ]]; then
+        find "$workdir" -maxdepth 1 -name '*.tmp' -exec rm -f {} \;
+    fi
 }
 
 # default dependency finder
@@ -297,8 +299,8 @@ function get_module_versions {
         return;
     fi
 
-    modules=$(mktemp)
-    
+    modules=$(make_temp)
+
     sort -u "$infile" | perl -npe 's/^perl\(//; s/\)\s*$//;' >$modules;
 
     while read -r a; do 
@@ -370,6 +372,8 @@ function executables() {
 # +-------------------------+
 
 set -euo pipefail
+declare -a CLEANFILES=()
+trap cleanup EXIT
 
 # optional
 GIT=$(command -v git || true);
@@ -608,7 +612,8 @@ destdir="${destdir:-$(pwd)}"
 git_project="${git_project:-}"
 
 if [[ -n "$git_project" ]]; then
-    tmp_gitdir=$(mktemp -d)
+    tmp_gitdir=$(make_temp -d)
+
     PROJECT_HOME="$tmp_gitdir"
     $GIT clone $git_project $PROJECT_HOME
     cd $PROJECT_HOME
@@ -629,7 +634,7 @@ fi
 dependency_file="${dependency_file:-}"
 test_dependency_file="${test_dependency_file:-}"
 build_requires="${build_requires:-}"
-recommends_file="${recommends_files:-}"
+recommends_file="${recommends_file:-}"
 
 if [[ -n "$dependency_file" ]]; then
   if [[ "$dependency_file" != /* ]]; then
@@ -706,11 +711,7 @@ fi
 # program that will provide the dependency list
 PERL_REQUIRES="${PERL_REQUIRES:-perl_requires}"
 
-builddir=$(mktemp -d)
-
-
-trap cleanup EXIT
-
+builddir=$(make_temp -d)
 
 module_file="$(module2path $MODULE)"
 
@@ -747,12 +748,12 @@ elif [[ -n "$EXTRA" ]]; then
 fi
 
 workdir=$(pwd)
-package_files=$(mktemp)
+package_files=$(make_temp)
 
 ########################################################################
 # gather executables - files must be executable if they are going to be packaged
 ########################################################################
-exe_files=$(mktemp)
+exe_files=$(make_temp)
 
 # default is yes
 maxdepth="${maxdepth:-}"
@@ -761,9 +762,11 @@ if [ ! "$recurse_directories" = "yes" ]; then
     maxdepth='-maxdepth 1'
 fi
 
-all_files="$(mktemp)"
+bindir="${bindir:-}"
+all_files="$(make_temp)"
+
 executables $bindir $all_files
-EXEC_PATH=$bindir
+EXEC_PATH="$bindir"
 
 scriptsdir="${scriptsdir:-}"
 executables $scriptsdir $all_files
@@ -778,9 +781,6 @@ if [[ -n "$exclude_list" ]]; then
     filter_file_list $exe_files $exclude_list
 fi
 
-if [[ -z "$NOCLEANUP" ]]; then
-    rm $all_files
-fi
 
 ########################################################################
 # resources
@@ -791,7 +791,7 @@ if [[  -e "resources" ]]; then
 elif [[ -z "$RESOURCES" ]]; then
     if [[ -d "$PROJECT_HOME/.git" ]]; then
         URL="$(git config --get remote.origin.web || true)";
-        resources=$(mktemp)
+        resources=$(make_temp)
 
         URL=$URL perl -MJSON -e \
         'print JSON->new->pretty->encode({ repository => { web => "$ENV{URL}", type => "git" }, homepage => "", bugtracker => { web => ""}});' > $resources
@@ -813,7 +813,8 @@ else
     if [[ -s "$provides" ]]; then
         echo "$MODULE" >>$provides
         # build index once
-        _module_index=$(mktemp)
+        _module_index=$(make_temp)
+
         root="${PROJECT_HOME}/${perl5libdir}/"
         build_module_index "$root" "$_module_index"
         
@@ -918,7 +919,7 @@ if [[ -z "$provides" ]]; then
     cat ${workdir}/provides.tmp | perl -npe 's/\//::/g; s/\.pm$//;' | sort -u > ${workdir}/provides
 else
     # make sure provides is sorted
-    sorted_provides=$(mktemp)
+    sorted_provides=$(make_temp)
     sort -u provides > $sorted_provides;
     mv $sorted_provides provides
 fi
@@ -932,7 +933,8 @@ else
     has_perl_version=$(cat ${workdir}/requires.tmp | grep '^perl' | awk '{print $2}')
 fi
 
-depfile=$(mktemp)
+depfile=$(make_temp)
+
 awk '{print $1}' ${workdir}/requires.tmp | sort -u | grep -v '^perl' > $depfile
 
 # remove provided files from required list
@@ -950,8 +952,8 @@ if [[ -n "$testsdir" ]]; then
     if [[ -d "${PROJECT_HOME}/$testsdir" ]]; then
         TESTS_PATH="$testsdir"
 
-        testsfile=$(mktemp);
-
+        testsfile=$(make_temp);
+  
         find -L "${PROJECT_HOME}/$testsdir" -not -path '*/.git/*' -type f -name '*.t' > $testsfile
 
         if ! [[ -e "$testsfile" ]]; then
@@ -1031,8 +1033,6 @@ if [[ $recurse_directories = "yes" ]]; then
    RECURSE="--recurse";
 fi
 
-EXEC_PATH="${EXEC_PATH:-}"
-SCRIPT_PATH="${SCRIPT_PATH:-}"
 TESTS_PATH="${TESTS_PATH:-}"
 VERSION_FROM="${VERSION_FROM:-}"
 OVERWRITE="${OVERWRITE:-}"
@@ -1040,8 +1040,8 @@ RESOURCES="${RESOURCES:-}"
 PL_FILES="${PL_FILES:-}"
 EXTRA_OPTIONS="${EXTRA_OPTIONS:-}"
 RECOMMENDS="${RECOMMENDS:-}"
-TEST_REQUIRES="{TEST_REQUIRES:-}"
-BUILD_REQUIRES="{BUILD_REQUIRES:-}"
+TEST_REQUIRES="${TEST_REQUIRES:-}"
+BUILD_REQUIRES="${BUILD_REQUIRES:-}"
 REQUIRE_VERSION="${REQUIRE_VERSION:-}"
 RECURSE="${RECURSE:-}"
 MODULE_PATH="${MODULE_PATH:-}"
